Liberally scatter BOOST_CXX14_CONSTEXPR throughout
boostorg/rational pull request #28
Opened 2018-10-27 20:05 UTC by tonyelewis

Add `BOOST_CXX14_CONSTEXPR` throughout the code.

2018-10-27 20:10 UTC, tonyelewis commented
This is discussed in #29.

2018-10-27 20:22 UTC, jeking3 commented
CI as it stands right now will not properly test this.  Could you pull in the expanded `.travis.yml` from Boost.Assign?  Nothing else needed, just copy the file in from develop tip.  That will greatly expand the CI to include many more C++ language levels.

2018-10-27 20:23 UTC, jeking3 requested changes
CI needs updating to properly test.

2018-10-28 01:57 UTC, jeking3 commented
```
test/rational_test.cpp:1296:5:   instantiated from here
../../boost/rational.hpp:178:91: internal compiler error: in build_data_member_initialization, at cp/semantics.c:5553
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.
Preprocessed source stored into /tmp/cctRuDKY.out file, please attach this to your bugreport.
    "g++-4.6"   -std=c++0x -fvisibility-inlines-hidden -fPIC -m64 -O3 -finline-functions -Wno-inline -Wall -fvisibility=hidden  -DBOOST_ALL_NO_LIB=1 -DBOOST_CHRONO_STATIC_LINK=1 -DBOOST_CHRONO_THREAD_DISABLED -DBOOST_SYSTEM_STATIC_LINK=1 -DBOOST_TEST_NO_AUTO_LINK=1 -DBOOST_TIMER_STATIC_LINK=1 -DNDEBUG  -I"../.." -c -o "../../bin.v2/libs/rational/test/rational_test.test/gcc-4.6/release/cxxstd-0x-iso/visibility-hidden/rational_test.o" "test/rational_test.cpp"
...failed gcc.compile.c++ ../../bin.v2/libs/rational/test/rational_test.test/gcc-4.6/release/cxxstd-0x-iso/visibility-hidden/rational_test.o...
```

2018-10-28 05:13 UTC, tonyelewis commented
So it looks like there was an internal compiler error in GCC 4.6 and problems in the test framework in a UBSan build. Neither of these look like direct consequences of the changes. I've submitted #30 in which I've copied the `.travis.yml` from Boost Assign to check that these tests were passing without this PR's changes.

2018-10-28 08:14 UTC, jzmaddock commented
CI failures not withstanding, yes please to more constexpr!

I'm sure there are other C++11/14 features that can be leveraged here (noexcept, moves?)

2018-10-29 17:50 UTC, tonyelewis commented
From what I can see, PR #32 also experiences the same failures so I don't think the changes in this PR's original commit are making anything worse.

2018-10-29 18:46 UTC, jeking3 commented
Thanks, let's go back to this PR without the expanded CI and I will merge it, and we'll deal with the expanded CI separately.

2018-10-29 19:29 UTC, tonyelewis commented
OK. Any preference whether I force-remove the last commit or add another commit that reverts it?

2018-10-29 20:00 UTC, jeking3 commented
I would remove it entirely through a rebase, dropping it, and force push.

2018-10-29 20:11 UTC, tonyelewis commented
OK. I've removed the last commit entirely.

2018-10-29 20:23 UTC, merged

2018-11-01 19:50 UTC, tonyelewis commented
Thanks. I've just submitted PR #32 that follows up on some of these issues.